### PR TITLE
Update os.pashm

### PR DESCRIPTION
**Pull request by mehanalavimajd**
I have added a few functions and variables in os.pashm

### CODE REVIEW

**Comment by parsampsh** [comment]
Also there is some other problems. I'll review and fix them later.

**Comment by mehanalavimajd** [comment]
Ok

**Comment by parsampsh** [comment]
I'll fixed the problems. only add the documentation to merge it.(add it in `doc/10_modules/06_os.md`).

**Comment by mehanalavimajd** [comment]
Ok , thank you . I'll do that

**Comment by mehanalavimajd** [comment]
I did it

**Comment by parsampsh** [comment]
Thanks.

**Comment by mehanalavimajd** [comment]
Your welcome.(I think i will create math library after 5 or 6 days)

**Pull request merged**
