### PR TITLE
Changing curdir to pwd

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Comment by parsampsh** [comment]
Hello mehan. The `curdir` means the `current directory`. This variable shows current directory symbol `.`. What are you meaning about `pwd`?

**Comment by mehanalavimajd** [comment]
In Unix-like and some other operating systems, the pwd command writes the full pathname of the current working directory to the standard output

**Comment by parsampsh** [comment]
So, to be compatible with the Python, I think the better name is the same `curdir`. But, you can add a new variable named `$pwd` and put the full path of the current working directory using `py_load_module('os')->getcwd()`. Then i merge it. also we need the documentation and test for it. I'm waiting for your changes.
Thanks.

**Comment by mehanalavimajd** [comment]
I have made changes now.

**Comment by parsampsh** [comment]
Thanks for ur PR.

**Pull request merged**
