### PR TITLE
Change the logo

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Comment by parsampsh** [comment]
Why?

**Comment by mehanalavimajd** [comment]
In my opinion this logo is more beautiful than a "P"

**Comment by parsampsh** [comment]
Yes its beautiful.
But this should be a svg file.
@sami2020pro whats your opinion?

**Comment by parsampsh** [comment]
Well. i cleaned up the patch. but i'm not sure for merging this. we should think more and ask others opinion.

**Comment by parsampsh** [comment]
https://github.com/mehanalavimajd/pashmak/blob/master/logo.svg

**Comment by parsampsh** [comment]
or

**Comment by mehanalavimajd** [comment]
Ok I will wait for others.

**Comment by amirghazi87** [comment]
I like old logo

**Comment by mehanalavimajd** [comment]
Ok

**Comment by mehanalavimajd** [comment]
@sami2020pro what about you?

**Comment by amirghazi87** [comment]
What has that got to do with pashmak? What does the new logo mean?

**Comment by parsampsh** [comment]
Well. i also think the old logo is better. but i have a idea. we can use this logo for Parham package manager!

**Comment by mehanalavimajd** [comment]
> Well. i also think the old logo is better. but i have a idea. we can use this logo for Parham package manager!

Very perfect idea

**Comment by sami2020pro** [comment]
I think the new logo is better for `Parham` but the constructive opinion is also important :+1:

**Review by sami2020pro — COMMENTED** [review]
I like the new logo but the old **Pashmak** logo is also suitable, but we can have two logos for **Pashmak** but I do not recommend this, I think this logo is suitable for `Parham`.

**Comment by parsampsh** [comment]
So, please send a PR for parham.

**Pull request closed without merging**
