### PR TITLE
adding regex to pashmak

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
any language need a regular library

### CODE REVIEW

**Comment by parsampsh** [comment]
Thank you so much! it needs some small fixes. i do them later then i merge it.

**Comment by parsampsh** [comment]
Only pending documentation and test.

**Comment by parsampsh** [comment]
@PooiaFerdowsi can you add documentation and test for this PR please?
then we can merge it :)

**Comment by PooiaFerdowsi** [comment]
Yes I will add document :+1: 
but I don't know about tests :-1:

**Comment by PooiaFerdowsi** [comment]
but when I click on edit file I go to my fork . How I do ?
Thanks

**Comment by PooiaFerdowsi** [comment]
Oh I see test Okay I create tests
:+1: :+1: :+1: :+1:

**Comment by PooiaFerdowsi** [comment]
I add document but when I try for add tests I get error

I don't know how to fix it 

can you fix please ?

**Comment by PooiaFerdowsi** [comment]
I don't know but my tests don't work correctly

**Comment by PooiaFerdowsi** [comment]
please yourself add tests
thanks

**Comment by parsampsh** [comment]
OK. i'll cleanup it later

**Comment by parsampsh** [comment]
Thanks. i merged it

**Pull request merged**
