### PR TITLE
Update __init__.pashm

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
سلام من دوست دارم سر درست این ماژول باشم این هم یک دستور مشترک بش و بچ

### CODE REVIEW

**Comment by parsampsh** [comment]
are you sure this function works correct? whats target of this function?

**Comment by PooiaFerdowsi** [comment]
تارگت آو دیس فانکشن ایز پرینت این کنسول ذه تکست ولیو
I.will.add.other.commands.like.mkdir

**Comment by parsampsh** [comment]
So currently this function does not print something and runs the argument as a shell command :|
This should be changed to `println $txt`.
But anyway, we have `println`, why this is needed?

**Comment by mehanalavimajd** [comment]
This wouldnt work you have to change it to 
```bash 
system(echo($txt))
```

**Review by mehanalavimajd — CHANGES_REQUESTED** [review]
You have to use : 
```bash
System(echo($txt))
```

**Comment by PooiaFerdowsi** [comment]
کلوز

**Pull request closed without merging**
