### PR TITLE
Add string standard library

### PR DESCRIPTION
**Pull request by sami2020pro**
I made the string standard library, and has **seven** functions in namespace.

example

```bash
println(concat('pashm', 'ak'))
println(remove_last('pashmak'))
println(remove_first('pashmak'))
println(length('pashmak'))
println(cut('pashmak', 1, 4))
println(upcase('pashmak'))
println(lowcase('PASHMAK'))
```

output

```html
pashmak
pashma
ashmak
7
ash
PASHMAK
pashmak
```

I will cooperate more with **Pashmak** soon (|\-\-|) :v:

Just a ___POINT___:
<p>
I will soon write a complete encyclopedia and research for those who want to be in the development of Pashmak, which will make the development process better and easier.
</p>

<br />

:point_right: IF source have problem please merge this pull request and FIX it.

### CODE REVIEW

**Comment by parsampsh** [comment]
Thank you so much! i'll add test for it.

**Comment by parsampsh** [comment]
Only documentation is needed. please add it in `doc/10_modules/09_string.md`.

**Comment by sami2020pro** [comment]
It does not have many documents, you can use the example(you can see in up) yourself.

**Comment by parsampsh** [comment]
I added it. thanks

**Pull request merged**
