### PR TITLE
Rename CHANGELOG.md to CHANGELOG/index.md

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**

### CODE REVIEW

**Comment by amirghazi87** [comment]
CHanelog.md is a standard for github

**Comment by mehanalavimajd** [comment]
@amirghazi87 is right

**Comment by PooiaFerdowsi** [comment]
its standard for github but no standard for github.io 
go to pashmaklang.github.io/pashmak/CHANGELOG.md
its std ?
no but index.md is index.html and if go to a path like of /any and be a directory redirect to /any/

**Comment by parsampsh** [comment]
Hi. no. as others said, this is not standard.

**Pull request closed without merging**
