### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Comment by parsampsh** [comment]
Hi. Its not necessary.

**Comment by mehanalavimajd** [comment]
But this is more readable

**Comment by parsampsh** [comment]
Ok.

**Comment by parsampsh** [comment]
We should send it to `0.7`

**Comment by parsampsh** [comment]
Please send it to branch `0.7`

**Comment by parsampsh** [comment]
So, i fixed it. do not send it to master. Thank you!

**Pull request merged**
