### PR TITLE
Adding 3.10 python in workflow

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Comment by mehanalavimajd** [comment]
it seems github know 3.10 as 3.1

**Comment by parsampsh** [comment]
Yes. It's so messed up. But i think there is a solution.

**Comment by parsampsh** [comment]
Put quotes around the `3.10` -> `"3.10"`. and also please send this again based on branch 0.8. Thank you

**Comment by mehanalavimajd** [comment]
I'm gonna make another pr

**Pull request closed without merging**
