### PR TITLE
Update program.py

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
Type list also available

### CODE REVIEW

**Comment by parsampsh** [comment]
First point is that you should use `and` instead of `or` in this case.
but about this:
```bash
import 'foo', 'bar'
# after you change:
import 'foo', 'bar'
import ['foo', 'bar']
```
I think no one does not need using `[]` brackets in the import syntax.

But anyway, first, change the branch to `0.8` instead of `master`, and also fix the `or` bug in your condition.
then i'll merge it. thanks

**Comment by PooiaFerdowsi** [comment]
Yes, Anyone can make a mistake :ok: ?

Don't need I change it :smile: ( I don't can find sticker )

I think no one does not need using [] brackets in the import syntax. see following

think to a code like composer dependency manager that return list of libraries as list . How import them ?

**Comment by parsampsh** [comment]
Yes i think so the brackets are not needed :)
i'll close this.
Whats your mean about the last line? :)

**Comment by PooiaFerdowsi** [comment]
See following code

```
$i = ["ext","foo","bar"]

import $i
```

**Comment by parsampsh** [comment]
> See following code
> 
> ```
> $i = ["ext","foo","bar"]
> 
> import $i
> ```

So we can replace it with:

```bash
$i = 'ext', 'foo', 'bar'
```

But anyway, i'll reopen it.

**Comment by parsampsh** [comment]
But if you can, please send this PR again. because the code base of branch `master` is changed and i cannot merge it to the master. you should send this pull request to the `0.8` branch.

**Comment by PooiaFerdowsi** [comment]
I change the base & resend another pull request

**Comment by parsampsh** [comment]
ok. i merged that. i'll close this one.

**Pull request closed without merging**
