### PR TITLE
end KWD

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
if you don't have plan for end keyword , I have a plan named Pull Request ( Why you say PR to pull request? )

also it is Pashmak 100th pull request

and I change master to 0.8

### CODE REVIEW

**Comment by parsampsh** [comment]
Hi Pooia, thanks for this PR.
I'm not sure this works, but it looks good.
But you should make the changes on the `master` and send PR to the `master` because this is a new feature.
pls send this to master, then we'll work on this more.
Thanks

**Comment by parsampsh** [comment]
Oh wait, base was changed without conflict. don't close this, its ok.
I'll review and test it.

**Comment by parsampsh** [comment]
So, i reviewed the code, this is not working. i'll keep this PR opened, we can work on this feature on this PR.

**Comment by PooiaFerdowsi** [comment]
I am sorry for this mistake ( I forget or forgot )

I don't know how do I

**Comment by PooiaFerdowsi** [comment]
how I do?

**Comment by PooiaFerdowsi** [comment]
oh . what I do ?

**Comment by parsampsh** [comment]
Nothing for now. we'll work on it later.

**Comment by parsampsh** [comment]
I'm involved in school exams for now.

**Comment by parsampsh** [comment]
I'm gonna close this PR. I've got plan to work on this feature and I make a new PR later.

**Pull request closed without merging**
