### PR TITLE
Add @doc for $pi

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Comment by parsampsh** [comment]
Hi. the variables haven't docstring in Pashmak.

**Comment by mehanalavimajd** [comment]
> Hi. the variables haven't docstring in Pashmak.

Why?

**Comment by parsampsh** [comment]
> > Hi. the variables haven't docstring in Pashmak.
> 
> Why?

Because they haven't :) command `@doc` does not set docstring for variables. docstring is only for functions and classes.

**Comment by mehanalavimajd** [comment]
Ok :(

**Pull request closed without merging**
